name: CI Frontend

on:
  pull_request:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  push:
    branches:
      - main
    paths:
      - 'starter/frontend/**'
  workflow_dispatch: # Cho phép chạy workflow này thủ công

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./starter/frontend
        run: npm install

      - name: Run eslint
        working-directory: ./starter/frontend
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        working-directory: ./starter/frontend
        run: npm install

      - name: Run tests
        working-directory: ./starter/frontend
        run: npm run test

  build:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for frontend
        working-directory: ./starter/frontend
        run: docker build -t frontend:latest .
